accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from accounts import views
from accounts.forms import LoginForm

urlpatterns = [
    url(r'register/', views.register, name='register'),
    url(r'login/', views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/accounts/login/'}, name='logout'),
]

course_pick/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from course_pick.views import homepage

urlpatterns = [
    # Examples:
    # url(r'^$', 'course_pick.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', homepage, name='homepage'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', namespace='courses')),
]

courses/urls.py
from django.conf.urls import url

from courses import views

urlpatterns = [
    url(r'^add/$', views.add_course, name='add'),
    url(r'^edit/(?P<course_id>.*)', views.edit_course, name='edit_course'),
    url(r'^pick/$', views.pick_course, name='pick'),
    url(r'^drop/$', views.drop_course, name='drop'),
    url(r'^delete/$', views.delete_course, name='delete'),
    url(r'^search/', views.search_course, name='search'),
    url(r'^student/$', views.student_view, name='student_view'),
    url(r'^teacher/$', views.teacher_view, name='teacher_view'),
    url(r'^manager/$', views.manager_view, name='manager_view'),
    url(r'^add/teacher/(?P<course_id>.*)', views.add_course_teacher, name='add_course_teacher'),
    url(r'^add/coursetime/(?P<course_id>.*)', views.add_coursetime, name='add_coursetime'),
    url(r'^add/exam/(?P<course_id>.*)', views.add_exam, name='add_exam'),
    url(r'^detail/(?P<course_id>.*)', views.detail, name='detail'),
    url(r'^extra/(?P<course_id>.*)', views.extra_info, name='extra_info'),
    url(r'^clear_teacher/', views.clear_teacher, name='clear_teacher'),
    url(r'^clear_coursetime/', views.clear_coursetime, name='clear_coursetime'),
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import User

class Student(models.Model):
    """
    Student information
    """
    id = models.CharField(max_length=20, primary_key=True)
    user = models.OneToOneField(User)
    name = models.CharField(max_length=20)

    user_type = 'student'

    def __unicode__(self):
        return "S: %s_%s" % (self.id, self.name)

class Teacher(models.Model):
    """
    Teacherr information
    """
    id = models.CharField(max_length=20, primary_key=True)
    user = models.OneToOneField(User)
    name = models.CharField(max_length=20)
    title = models.CharField(max_length=20)

    user_type = 'teacher'

    def __unicode__(self):
        return "T: %s_%s_%s" % (self.id, self.name, self.title)

class Manager(models.Model):
    """
    Manager information
    """
    id = models.CharField(max_length=20, primary_key=True)
    user = models.OneToOneField(User)
    name = models.CharField(max_length=20)

    user_type = 'manager'

    def __unicode__(self):
        return "M: %s_%s" % (self.id, self.name)

accounts/forms.py
# encoding: utf-8

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.forms.utils import ErrorList

class LoginForm(forms.Form):
    username = forms.CharField(error_messages={'required': '用户名不能为空'}, max_length=30)
    password = forms.CharField(widget=forms.PasswordInput, error_messages={'required': '密码不能为空'})

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            self.user_cache = authenticate(username=username, password=password)
            if self.user_cache is None:
                self.add_error('password', '请输入正确的用户名、密码')

        return self.cleaned_data

class RegisterForm(forms.Form):
    id = forms.CharField(error_messages={'required': '学号/工号不能为空', 'max_length':'最多是 11 个字'}, max_length = 11)
    name = forms.CharField(error_messages={'required': '姓名不能为空', 'max_length': '最多是 10 个字'}, max_length=20)
    password = forms.CharField(widget=forms.PasswordInput, error_messages = {'required': '密码不能为空', 'min_length':'至少是 6 个字符', 'max_length':'最多是 16 个字符'}, min_length = 6, max_length = 16)
    confirm_password = forms.CharField(widget=forms.PasswordInput, error_messages = {'required': '确认密码不能为空', 'min_length':'至少是 6 个字符', 'max_length':'最多是 16 个字符'}, max_length = 16)
    title = forms.CharField(max_length=20, required=False)

    TYPE_CHOICES = (
        ('student', '学生',),
        ('teacher', '教师',),
        ('manager', '教务员',),
    )
    type = forms.ChoiceField(widget=forms.Select, choices=TYPE_CHOICES)

    def clean_id(self):
        id = self.cleaned_data['id']
        exists = User.objects.filter(username = id).count() > 0
        if exists:
            self.add_error('id', '该学号/工号已被使用，请重新输入')
        return id

    def clean(self):
        if ('confirm_password' in self.cleaned_data) and ('password' in self.cleaned_data):
            if (self.cleaned_data['confirm_password'] != self.cleaned_data['password']):
                self._errors["confirm_password"] = ErrorList(['密码和确认密码不一致'])
                del self.cleaned_data['password']
                del self.cleaned_data['confirm_password']

        return self.cleaned_data

accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.models import User, Permission
from django.contrib.auth import authenticate, login as auth_login

from django.template.response import TemplateResponse

from accounts.models import Student, Teacher, Manager
from accounts.forms import RegisterForm, LoginForm

STUDENT_PERMISSION = list(Permission.objects.filter(codename='change_course'))
TEACHER_PERMISSION = list(Permission.objects.filter(codename='change_course'))
MANAGER_PERMISSION = list(Permission.objects.filter(codename__endswith='course')) + list(Permission.objects.filter(codename__endswith='exam')) + list(Permission.objects.filter(codename__endswith='coursetime'))

def register(request):
    if hasattr(request, 'user'):
        if request.user.is_authenticated():
            return redirect('/')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            id = form.cleaned_data['id']
            name = form.cleaned_data['name']
            password = form.cleaned_data['password']
            type = form.cleaned_data['type']
            new_user = User.objects.create_user(username=id, password=password)

            if type == Student.user_type:
                new_student = Student.objects.create(id = id, user=new_user, name=name)
                new_user.user_permissions = STUDENT_PERMISSION

            if type == Teacher.user_type:
                title = form.cleaned_data['title']
                new_teacher = Teacher.objects.create(id = id, user=new_user, name=name, title=title)
                new_user.user_permissions = TEACHER_PERMISSION

            if type == Manager.user_type:
                new_manager = Manager.objects.create(id = id, user=new_user, name=name)
                new_user.user_permissions = MANAGER_PERMISSION

            user = authenticate(username=id, password=password)
            auth_login(request, user)
            return redirect('/')
    else:
        form = RegisterForm()

    context = {
        'form': form
    }
    return TemplateResponse(request, "accounts/register.html", context)

def login(request):
    if hasattr(request, 'user'):
        if request.user.is_authenticated():
            return redirect('/')
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user:
                auth_login(request, user)
                return redirect('/')
    else:
        form = LoginForm()

    context = {
        'form': form
    }
    return TemplateResponse(request, "accounts/login.html", context)

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block title %}登录{% endblock %}

{% block content %}
<div>
    <div class="ui two column doubling ui grid">
        <div class="ui column">
            <div class="ui segment">
                <form method="post" action="" class="ui form">
                    {% csrf_token %}
                    <h4 class="ui dividing header">登录</h4>
                    <div class="field">
                        <label>用户名</label>
                        <div class="ui input icon">
                            <i class="user icon"></i>
                            {{ form.username }}
                        </div>
                        <div class="ui error">
                            {{ form.username.errors }}
                        </div>
                    </div>
                    <div class="field">
                        <label>密码</label>
                        <div class="ui input icon">
                            <i class="lock icon"></i>
                            {{ form.password }}
                        </div>
                        <div class="ui error">
                            {{ form.password.errors }}
                        </div>
                    </div>
                    <div class="ui two fluid buttons">
                        <button class="ui green button">登录</button>
                        <a class="ui vertical animated button" href="/accounts/register/">
                            <div class="visible content">还没帐号？</div>
                            <div class="hidden content">注册</div>
                        </a>
                    </div>
                </form>
            </div>
        </div>
        <div class="column">
            <div class="ui segment">
                <p>欢迎来到选课系统，请登录</p>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block script %}
    {% endblock %}

    {% block isFixed %}
    fixed
    {% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% block title %}注册{% endblock %}

{% block content %}
<div>
    <div class="ui two column doubling ui grid">
        <div class="ui column">
            <div class="ui segment">
                <form action="" method="post" class="ui form">
                    {% csrf_token %}
                    <h4 class="ui dividing header">注册</h4>
                    <div class="field">
                        <label>学号/工号</label>
                        <div class="ui icon input">
                            <i class="info icon"></i>
                            {{ form.id }}
                        </div>
                        <div>
                            {{ form.id.errors }}
                        </div>
                    </div>
                    <div class="field">
                        <label>姓名</label>
                        <div class="ui icon input">
                            <i class="user icon"></i>
                            {{ form.name }}
                        </div>
                        <div>
                            {{ form.name.errors }}
                        </div>
                    </div>
                    <div class="field">
                        <label>密码</label>
                        <div class="ui icon input">
                            <i class="lock icon"></i>
                            {{ form.password }}
                        </div>
                        <div>
                            {{ form.password.errors }}
                        </div>
                    </div>
                    <div class="field">
                        <label>确认密码</label>
                        <div class="ui icon input">
                            <i class="repeat icon"></i>
                            {{ form.confirm_password }}
                        </div>
                        <div>
                            {{ form.confirm_password.errors }}
                        </div>
                    </div>
                    <div class="field">
                        <label>用户组</label>
                        {{ form.type }}
                    </div>
                    <div id="title_div" style="display:none;" class="field">
                        <label>职称</label>
                        <div class="ui icon input">
                            <i class="tag icon"></i>
                            {{ form.title }}
                        </div>
                    </div>
                    <div class="ui two fluid buttons">
                        <button class="ui green button">注册</button>
                        <a class="ui animated button" href="/accounts/login/">
                            <div class="visible content">已有帐号？</div>
                            <div class="hidden content">登录</div>
                        </a>
                    </div>
                </form>
            </div>
        </div>
        <div class="column">
            <div class="ui segment">
                <p>欢迎来到选课系统，请注册</p>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

{% block script %}
<script>
    $("#id_type").addClass("ui selection dropdown");
     $('select.dropdown')
                 .dropdown();
    $("#id_type").change(function() {
    if ($("#id_type").val() == "teacher") {
        $('#title_div').show()
    } else {
        $('#title_div').hide()
    }
    });
</script>
{% endblock %}

{% block isFixed %}
fixed
{% endblock %}