course_pick/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from course_pick.views import homepage

urlpatterns = [
    # Examples:
    # url(r'^$', 'course_pick.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', homepage, name='homepage'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls', namespace='courses')),
]

courses/urls.py
from django.conf.urls import url

from courses import views

urlpatterns = [
    url(r'^add/$', views.add_course, name='add'),
    url(r'^edit/(?P<course_id>.*)', views.edit_course, name='edit_course'),
    url(r'^pick/$', views.pick_course, name='pick'),
    url(r'^drop/$', views.drop_course, name='drop'),
    url(r'^delete/$', views.delete_course, name='delete'),
    url(r'^search/', views.search_course, name='search'),
    url(r'^student/$', views.student_view, name='student_view'),
    url(r'^teacher/$', views.teacher_view, name='teacher_view'),
    url(r'^manager/$', views.manager_view, name='manager_view'),
    url(r'^add/teacher/(?P<course_id>.*)', views.add_course_teacher, name='add_course_teacher'),
    url(r'^add/coursetime/(?P<course_id>.*)', views.add_coursetime, name='add_coursetime'),
    url(r'^add/exam/(?P<course_id>.*)', views.add_exam, name='add_exam'),
    url(r'^detail/(?P<course_id>.*)', views.detail, name='detail'),
    url(r'^extra/(?P<course_id>.*)', views.extra_info, name='extra_info'),
    url(r'^clear_teacher/', views.clear_teacher, name='clear_teacher'),
    url(r'^clear_coursetime/', views.clear_coursetime, name='clear_coursetime'),
]

courses/models.py
# encoding: utf-8

from django.db import models

from accounts.models import Student, Teacher

class Course(models.Model):
    """
    Course informations
    """
    id = models.CharField(max_length=20, primary_key=True)
    name = models.CharField(max_length=40)
    college = models.CharField(max_length=40)
    classroom = models.CharField(max_length=40)
    score = models.DecimalField(max_digits=3, decimal_places=1)
    max_student_number = models.IntegerField()
    remark = models.CharField(max_length=100)
    student = models.ManyToManyField(Student)
    teacher = models.ManyToManyField(Teacher)

    def __unicode__(self):
        return self.name

    def get_student_count(self):
        return self.student.all().count()

    def get_teacher_info(self):
        result = []
        teachers = self.teacher.all()
        for teacher in teachers:
            result.append({
                'name': teacher.name,
                'title': teacher.title,
            })
        return result

    def get_coursetime_info(self):
        result = []
        coursetimes = self.coursetime_set.all()
        for coursetime in coursetimes:
            result.append({
                'weekday': coursetime.weekday,
                'begin': coursetime.begin,
                'end': coursetime.end,
            })
        return result

    def get_exam_info(self):
        try:
            exam = self.exam
        except:
            return None
        EXAM_METHOD_CHOICES = {
            'KJ': '开卷',
            'BJ': '闭卷',
            'LW': '论文',
        }
        result = {
            'method': EXAM_METHOD_CHOICES[exam.method],
            'date': exam.date,
            'time': exam.time,
        }
        return result

class Exam(models.Model):
    """
    A Course's Final Exam informations
    """
    KJ = 'KJ'
    BJ = 'BJ'
    LW = 'LW'
    EXAM_METHOD_CHOICES = (
        (KJ, '开卷'),
        (BJ, '闭卷'),
        (LW, '论文'),
    )
    course = models.OneToOneField(Course, primary_key=True)
    method = models.CharField(choices=EXAM_METHOD_CHOICES, default=BJ, max_length=10)
    date = models.DateField()
    time = models.TimeField(null=True, blank=True)

    def __unicode__(self):
        return self.course.__unicode__() + '_' + self.get_method_display()

class CourseTime(models.Model):
    """
    The time a course is schedueled
    """
    WEEKDAY_CHOICES = (
        ('Mon', '周一'),
        ('Tue', '周二'),
        ('Wed', '周三'),
        ('Thu', '周四'),
        ('Fri', '周五'),
        ('Sat', '周六'),
        ('Sun', '周日'),
    )
    COURSE_TIME_CHOICES = (
        (1, '第 1 节'),
        (2, '第 2 节'),
        (3, '第 3 节'),
        (4, '第 4 节'),
        (5, '第 5 节'),
        (6, '第 6 节'),
        (7, '第 7 节'),
        (8, '第 8 节'),
        (9, '第 9 节'),
        (10, '第 10 节'),
        (11, '第 11 节'),
        (12, '第 12 节'),
        (13, '第 13 节'),
        (14, '第 14 节'),
    )
    course = models.ForeignKey(Course)
    weekday = models.CharField(max_length=3, choices=WEEKDAY_CHOICES)
    begin = models.PositiveSmallIntegerField(choices=COURSE_TIME_CHOICES)
    end = models.PositiveSmallIntegerField(choices=COURSE_TIME_CHOICES)

    def __unicode__(self):
        return self.course.__unicode__() + '_' + self.get_weekday_display()

    def get_span(self):
        return self.end - self.begin + 1

courses/views.py
# encoding: utf-8

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import permission_required, login_required

from django.http import HttpResponse

from django.template.response import TemplateResponse

from accounts.models import Student, Teacher

from courses.models import Course, Exam, CourseTime
from courses.forms import *

@permission_required('courses.add_course')
def add_course(request):
    if request.method == 'POST':
        form = AddCourseForm(request.POST)
        if form.is_valid():
            new_course = Course.objects.create(
                id                 = form.cleaned_data['id'],
                name               = form.cleaned_data['name'],
                college            = form.cleaned_data['college'],
                classroom          = form.cleaned_data['classroom'],
                score              = form.cleaned_data['score'],
                max_student_number = form.cleaned_data['max_student_number'],
                remark             = form.cleaned_data['remark'],
            )

            return redirect('/courses/extra/'+new_course.id)
    else:
        form = AddCourseForm()

    context = {
        'form': form,
    }
    return TemplateResponse(request, 'courses/add_course.html', context)

@permission_required('courses.change_course')
def edit_course(request, course_id):
    if request.method == 'POST':
        form = EditCourseForm(request.POST)
        if form.is_valid():
            course = Course.objects.filter(id=course_id)
            course.update(
                name               = form.cleaned_data['name'],
                college            = form.cleaned_data['college'],
                classroom          = form.cleaned_data['classroom'],
                score              = form.cleaned_data['score'],
                max_student_number = form.cleaned_data['max_student_number'],
                remark             = form.cleaned_data['remark'],
            )
        else:
            form.id = course_id
            context = {
                'form': form,
            }
            return render(request,  'courses/detail.html', context)
    return redirect('/courses/detail/' + course_id)

def extra_info(request, course_id, teacher_form=AddCourseTeacherForm(), coursetime_form=AddCourseTimeForm(), exam_form=None):
    course = Course.objects.get(id=course_id)
    if exam_form is None:
        try:
            exam = course.exam
            exam_form = AddExamForm(
                {
                    'course_id': course.id,
                    'method': exam.method,
                    'date': exam.date,
                    'time': exam.time,
                }
            )
        except:
            exam_form = AddExamForm()
    context = {
        'course_id': course_id,
        'teacher_form': teacher_form,
        'coursetime_form': coursetime_form,
        'exam_form': exam_form,
    }
    return TemplateResponse(request, 'courses/extra_info.html', context)

@permission_required('courses.change_course')
def add_course_teacher(request, course_id):
    if request.method == 'POST':
        form = AddCourseTeacherForm(request.POST)
        if form.is_valid():
            teacher_id = form.cleaned_data['teacher_id']
            course = Course.objects.get(id=course_id)
            teacher = Teacher.objects.get(id=teacher_id)
            course.teacher.add(teacher)
            form = AddCourseTeacherForm()
            form.success = '添加教师成功'
    else:
        form = AddCourseTeacherForm()
    return extra_info(request, course_id, form)

@permission_required('courses.add_coursetime')
def add_coursetime(request, course_id):
    if request.method == 'POST':
        data = request.POST.dict()
        data['course_id'] = course_id
        form = AddCourseTimeForm(data)
        if form.is_valid():
            course = Course.objects.get(id=course_id)
            weekday = form.cleaned_data['weekday']
            begin = form.cleaned_data['begin']
            end = form.cleaned_data['end']
            coursetime = CourseTime.objects.create(
                course=course,
                weekday=weekday,
                begin=begin,
                end=end,
            )
            form = AddCourseTimeForm()
            form.success = '添加上课时间成功'
    else:
        form = AddCourseTimeForm()
    return extra_info(request, course_id, coursetime_form=form)

@permission_required('courses.add_exam')
def add_exam(request, course_id):
    if request.method == 'POST':
        data = request.POST.dict()
        data['course_id'] = course_id
        form = AddExamForm(data)
        if form.is_valid():
            course = Course.objects.get(id=course_id)
            method = form.cleaned_data['method']
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            try:
                exam = Exam.objects.get(course=course)
                exam.course=course
                exam.method=method
                exam.date=date
                exam.time=time
            except:
                exam = Exam(
                    course=course,
                    method=method,
                    date=date,
                    time=time,
                )
            finally:
                exam.save()
            form.success = '修改考试信息成功'
    else:
        form = AddExamForm()
    return extra_info(request, course_id, exam_form=form)

@permission_required('courses.delete_course')
def delete_course(request):
    if request.method == 'POST':
        id = request.POST['id']
        course = Course.objects.get(id=id)
        course.delete()
    return redirect('/')

@login_required
def pick_course(request):
    if request.method == 'POST':
        form = PickCourseForm(request.POST)
        course_id = request.POST['course_id']
        if form.is_valid():
            student_id = form.cleaned_data['student_id']
            student = Student.objects.get(id=student_id)
            course = Course.objects.get(id=course_id)
            course.student.add(student)
            form.success = '选课成功'
    try:
        student = request.user.student
        if hasattr(form, 'success'):
            return student_view(request, form.success)
        else:
            return student_view(request, form['course_id'].errors[0])
    except:
        pass
    try:
        teacher = request.user.teacher
        if hasattr(form, 'success'):
            return teacher_view(request, form.success)
        else:
            if form['student_id'].errors:
                return teacher_view(request, form['student_id'].errors[0])
            else:
                return teacher_view(request, form['course_id'].errors[0])
    except:
        pass
    try:
        manager = request.user.manager
        return detail(request, course_id, form)
    except:
        pass
    return redirect('/')

@login_required
def drop_course(request):
    if request.method == 'POST':
        form = DropCourseForm(request.POST)
        course_id = request.POST['course_id']
        if form.is_valid():
            student_id = form.cleaned_data['student_id']
            student = Student.objects.get(id=student_id)
            course = Course.objects.get(id=course_id)
            course.student.remove(student)
            form.success = '退课成功'
    try:
        student = request.user.student
        if hasattr(form, 'success'):
            return student_view(request, form.success)
        else:
            return student_view(request, form['course_id'].errors[0])
    except:
        pass
    try:
        teacher = request.user.teacher
        if hasattr(form, 'success'):
            return teacher_view(request, form.success)
        else:
            if form['student_id'].errors:
                return teacher_view(request, form['student_id'].errors[0])
            else:
                return teacher_view(request, form['course_id'].errors[0])
    except:
        pass
    try:
        manager = request.user.manager
        return detail(request, course_id, drop_course_form=form)
    except:
        pass
    return redirect('/')

def search_course(request):
    search_content = request.GET['q']
    search_by_id = Course.objects.filter(id__icontains=search_content)
    search_by_course = Course.objects.filter(name__icontains=search_content)
    search_by_teacher = Course.objects.filter(teacher__name__icontains=search_content)
    search_by_college = Course.objects.filter(college__icontains=search_content)
    context = {
        'id_results': search_by_id,
        'teacher_results': search_by_teacher,
        'course_results': search_by_course,
        'college_results': search_by_college,
    }
    return TemplateResponse(request, "courses/search_results.html", context)

@login_required
def student_view(request, message=None):
    user = request.user
    try:
        student = user.student
    except:
        return redirect('/')
    WEEKDAY_ITER = {
        'Mon': 0,
        'Tue': 1,
        'Wed': 2,
        'Thu': 3,
        'Fri': 4,
        'Sat': 5,
        'Sun': 6,
    }
    picked_courses = student.course_set.all()
    class_table = [['' for j in range(7)] for i in range(14)]
    for picked_course in picked_courses:
        for course_time in picked_course.coursetime_set.all():
            class_table[course_time.begin-1][WEEKDAY_ITER[course_time.weekday]] = course_time
            for i in range(course_time.begin, course_time.end):
                class_table[i][WEEKDAY_ITER[course_time.weekday]] = None

    context = {
        'courses': picked_courses,
        'class_table': class_table,
        'message': message,
    }

    return TemplateResponse(request, 'courses/student.html', context)

@login_required
def teacher_view(request, message=None):
    user = request.user

    try:
        teacher = user.teacher
    except:
        return redirect('/')

    courses = teacher.course_set.all()

    context = {
        'courses': courses,

courses/templates/courses/detail.html
{% extends "base.html" %}

{% block title %}
课程信息
{% endblock %}

{% block content %}
<div class="ui two column grid" style="position: relative;">
    {% if user.manager %}
    <div class="four wide column">
        <div class="ui segment">
            {% if pick_course_form.errors %}
            <div class="ui message">
                {{ pick_course_form.errors }}
            </div>
            {% endif %}
            {% if drop_course_form.errors %}
            <div class="ui message">
                {{ drop_course_form.errors }}
            </div>
            {% endif %}
            {% if pick_course_form.success %}
            <div class="ui message">
                {{ pick_course_form.success }}
            </div>
            {% endif %}
            {% if drop_course_form.success %}
            <div class="ui message">
                {{ drop_course_form.success }}
            </div>
            {% endif %}
            <div class="ui top attached tabular menu">
                <a class="ui active item" id="pick_section">学生选课</a>
                <a class="ui item" id="drop_section">学生退课</a>
            </div>
            <form class="ui bottom attached segment form" action="/courses/pick/" method="post" id="pick_form">
                {% csrf_token %}
                <div class="field">
                    <label for="">选课学生学号</label>
                    <div class="ui input icon">
                        <i class="add user icon"></i>
                        {{ pick_course_form.student_id }}
                    </div>
                </div>
                <div class="field" style="display:none;">
                    <input name="course_id" value="{{ form.id }}"">
                </div>
                <button class="ui green button">提交</button>
            </form>

            <form class="ui bottom attached segment form" action="/courses/drop/" method="post" style="display:none;" id="drop_form">
                {% csrf_token %}
                <div class="field">
                    <label for="">退课学生学号</label>
                    <div class="ui input icon">
                        <i class="remove user icon"></i>
                        {{ drop_course_form.student_id }}
                    </div>
                </div>
                <div class="field" style="display:none;">
                    <input name="course_id" value="{{ form.id }}"">
                </div>
                <button class="ui green button">提交</button>
            </form>

            <form action="/courses/delete/" method="post" id="delete_form">
                {% csrf_token %}
                <input name="id" value="{{ form.id }}" style="display:none;">
                <div style="display:none;">
                    {{ form.name }}
                </div>
            </form>
        </div>

        <div class="ui segment">
            <h4 class="ui dividing header">学生列表</h4>
            {% if students %}
            <div class="scroll">
                <table class="ui celled table">
                    <thead>
                        <tr>
                            <th>学号</th>
                            <th>姓名</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in students %}
                        <tr>
                            <td>{{ student.id }}</td>
                            <td>{{ student.name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="ui message">
                目前没有学生选这门课
            </div>
            {% endif %}
        </div>
    </div>
    {% endif %}
    <div class="twelve wide column">
        <form class="ui segment form" action="/courses/edit/{{ form.id }}" method="post">
            {% csrf_token %}
            <h4 class="ui dividing header">课程信息</h4>
            <div class="two fields">
                <div class="field">
                    <label for="">课程编号</label>
                    <div class="ui input icon">
                        <i class="info icon"></i>
                        <input readonly name="id" value="{{ form.id }}">
                    </div>
                    {% if form.id.errors %}
                    <div class="ui message">
                        {{ form.id.errors }}
                    </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label for="">课程名称</label>
                    <div class="ui input icon">
                        <i class="book icon"></i>
                        {{ form.name }}
                    </div>
                    {% if form.name.errors %}
                    <div class="ui message">
                        {{ form.name.errors }}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="two fields">
                <div class="field">
                    <label for="">开课院系</label>
                    <div class="ui input icon">
                        <i class="student icon"></i>
                        {{ form.college }}
                    </div>
                    {% if form.college.errors %}
                    <div class="ui message">
                        {{ form.college.errors }}
                    </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label for="">上课教室</label>
                    <div class="ui input icon">
                        <i class="building icon"></i>
                        {{ form.classroom }}
                    </div>
                    {% if form.classroom.errors %}
                    <div class="ui message">
                        {{ form.classroom.errors }}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="two fields">
                <div class="field">
                    <label for="">学分</label>
                    <div class="ui input icon">
                        <i class="write icon"></i>
                        {{ form.score }}
                    </div>
                    {% if form.score.errors %}
                    <div class="ui message">
                        {{ form.score.errors }}
                    </div>
                    {% endif %}
                </div>
                <div class="field">
                    <label for="">最大学生人数</label>
                    <div class="ui input icon">
                        <i class="users icon"></i>
                        {{ form.max_student_number }}
                    </div>
                    {% if form.max_student_number.errors %}
                    <div class="ui message">
                        {{ form.max_student_number.errors }}
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="field">
                <label for="">备注</label>
                <div class="ui input icon">
                    {{ form.remark }}
                </div>
            </div>
            {% if user.manager %}
            <div class="ui buttons">
                <button class="ui green button">更改</button>
                <input type="submit" class="ui red button" form="delete_form" value="删除课程"></button>
            </div>
            {% endif %}
        </form>

        <div class="ui segment">
            {% if user.manager %}
            <a href="/courses/extra/{{ form.id }}">
                <h4>相关信息</h4>
            </a>
            {% else %}
            <h4>相关信息</h4>
            {% endif %}
            <div class="ui divider"> </div>
            <h5 class="ui dividing header">任职教师</h5>
            <div class="ui list">
                {% if teachers %}
                {% for teacher in teachers %}
                <div class="item">
                    <div class="header">
                        {{ teacher.name }}
                    </div>
                    {{ teacher.title }}
                </div>
                {% endfor %}
                {% else %}
                <div class="item">
                    <div class="header">
                        该课程尚未添加教师信息，请尽快添加
                    </div>
                </div>
                {% endif %}
            </div>
            <h5 class="ui dividing header">上课时间</h5>
            <div class="ui list">
                {% if coursetimes %}
                {% for coursetime in coursetimes %}
                <div class="item">
                    <div class="header">
                        {{ coursetime.weekday }}
                    </div>
                    {{ coursetime.begin }} - {{ coursetime.end }}
                </div>
                {% endfor %}
                {% else %}
                <div class="item">
                    <div class="header">
                        该课程尚未添加上课时间信息，请尽快添加
                    </div>
                </div>
                {% endif %}
            </div>
            <h5 class="ui dividing header">考试信息</h5>
            <div class="ui list">
                {% if exam %}
                <div class="item">
                    <div class="header">
                        {{ exam.method }}
                    </div>
                    {{ exam.date }}
                    {% if exam.time %}
                    {{ exam.time }}
                    {% endif %}
                </div>
                {% else %}
                <div class="item">
                    <div class="header">
                        该课程尚未添加上课时间信息，请尽快添加
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    {% if not user.manager %}
    <div class="four wide column">
        <div class="ui segment">
            <h4 class="ui dividing header">学生列表</h4>
            {% if students %}
            <div class="scroll">
                <table class="ui celled table">
                    <thead>
                        <tr>
                            <th>学号</th>
                            <th>姓名</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in students %}
                        <tr>
                            <td>{{ student.id }}</td>
                            <td>{{ student.name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="ui message">
                目前没有学生选这门课
            </div>
            {% endif %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

{% block script %}
<script>
 {% if not user.manager %}
 $('input').each(function() {
     $(this).attr('readonly', true);
 })
     $('#search_input').attr('readonly', false);
 $('#id_remark').attr('readonly', true);
 {% else %}
 $('#pick_section').click(function() {
     $('#drop_form').hide();
     $('#drop_section').removeClass("active");
     $('#pick_form').show();
     $('#pick_section').addClass("active");
 })
     $('#drop_section').click(function() {
         $('#pick_form').hide();
         $('#pick_section').removeClass("active");
         $('#drop_form').show();
         $('#drop_section').addClass("active");
     })
 {% endif %}
</script>

<style>
 .scroll {
     width: 100%;
     height: 290px;
     overflow: scroll;
 }
</style>
{% endblock %}

courses/templates/courses/extra_info.html
{% extends "base.html" %}

{% block title %}
课程相关信息
{% endblock %}

{% block content %}
<h1 class="ui dividing header">#<a href="/courses/detail/{{ course_id }}">{{ course_id }}</a> 相关信息</h1>
<div class="ui three column grid">
    <div class="four wide column">
        <form class="ui segment form" action="/courses/add/teacher/{{ course_id }}" method="post">
            {% csrf_token %}
            <h4 class="ui dividing header">添加教师</h4>
            <div class="field">
                <label for="">教师工号</label>
                <div class="ui input">
                    {{ teacher_form.teacher_id }}
                </div>
            </div>
            {% if teacher_form.errors %}
            <div class="ui message">
                {{ teacher_form.teacher_id.errors }}
            </div>
            {% endif %}
            {% if teacher_form.success %}
            <div class="ui message">
                {{ teacher_form.success }}
            </div>
            {% endif %}
            <div class="ui buttons">
                <button class="ui green button">添加</button>
                <input class="ui red button" name="" type="submit" value="重新分配教师" form="clear_teacher_form"/>
            </div>
        </form>

        <form action="/courses/clear_teacher/" method="post" id="clear_teacher_form">
            {% csrf_token %}
            <input name="course_id" value="{{ course_id }}" style="display:none;">
        </form>
    </div>

    <div class="four wide column">
        <form class="ui segment form" action="/courses/add/coursetime/{{ course_id }}" method="post">
            {% csrf_token %}
            <h4 class="ui dividing header">添加上课时间</h4>
            <div class="field">
                <label for="">星期</label>
                <div class="ui input">
                    {{ coursetime_form.weekday }}
                </div>
            </div>
            <div class="field">
                <label for="">开始时间</label>
                <div class="ui input">
                    {{ coursetime_form.begin }}
                </div>
            </div>
            <div class="field">
                <label for="">结束时间</label>
                <div class="ui input">
                    {{ coursetime_form.end }}
                </div>
            </div>
            {% if coursetime_form.errors %}
            <div class="ui message">
                {{ coursetime_form.errors }}
            </div>
            {% endif %}
            {% if coursetime_form.success %}
            <div class="ui message">
                {{ coursetime_form.success }}
            </div>
            {% endif %}
            <div class="ui buttons">
                <button class="ui green button">添加</button>
                <input class="ui red button" name="" type="submit" value="重新添加上课时间" form="clear_coursetime_form"/>
            </div>
        </form>

        <form action="/courses/clear_coursetime/" method="post" id="clear_coursetime_form">
            {% csrf_token %}
            <input name="course_id" value="{{ course_id }}" style="display:none;">
        </form>
    </div>

    <div class="eight wide column">
        <form class="ui segment form" action="/courses/add/exam/{{ course_id }}" method="post">
            {% csrf_token %}
            <h4 class="ui dividing header">考试信息</h4>
            <div class="field">
                <label for="">形式</label>
                <div class="ui input">
                    {{ exam_form.method }}
                </div>
            </div>
            <div class="field">
                <label for="">考试日期/论文截止</label>
                <div class="ui input">
                    {{ exam_form.date }}
                </div>
            </div>
            <div class="field" id="exam_time">
                <label for="">考试时间</label>
                <div class="ui input">
                    {{ exam_form.time }}
                </div>
            </div>
            {% if exam_form.errors %}
            <div class="ui message">
                {{ exam_form.errors }}
            </div>
            {% endif %}
            {% if exam_form.success %}
            <div class="ui message">
                {{ exam_form.success }}
            </div>
            {% endif %}
            <button class="ui green button">提交</button>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
 $('select').addClass("ui selection dropdown");
 $('select.dropdown').dropdown();
 function toggle_exam_time() {
     if ($("#id_method").val() != "LW") {
         $('#exam_time').show()
     } else {
         $('#exam_time').hide()
     }
 }
 toggle_exam_time()
 $("#id_method").change(toggle_exam_time);
</script>
{% endblock %}